### ISSUE TITLE
Providing record_name option for table, disables its distribution

### ISSUE THREAD

**Issue by aby2503** [beardedeagle/mnesiac#20]
## Version and Environment

Mnesiac:
OS/Distro:

## Expected behavior

After node connected to cluster, all tables will be processed, according to resolve_conflict policy

## Actual behavior

New node just initialized new tables

## Steps to reproduce

1. Create store with record_name option
2. Start cluster

## Additional info
Here's the code, which causes the problem
`

    local_cookies = get_table_cookies()
    remote_cookies = get_table_cookies(cluster_node)

    Enum.each(stores(), fn data_mapper ->
      case {local_cookies[data_mapper], remote_cookies[data_mapper]} do
        {nil, nil} ->
          apply(data_mapper, :init_store, [])

        {nil, _} ->
          apply(data_mapper, :copy_store, [])

        {_, nil} ->
          Logger.info("[mnesiac:#{node()}] #{inspect(data_mapper)}: no remote data to copy found.")
          {:error, :no_remote_data_to_copy}

        {_local, _remote} ->
          apply(data_mapper, :resolve_conflict, [cluster_node])
      end
    end)

`
Store
`
defmodule MnesiaNode.Store.Sessions do
  use Mnesiac.Store
  alias Common.Constants, as: CT

  def store_options() do
    [
      record_name: :sessions,
      type: :set,
      attributes: [:id, :value],
      storage_properties: [ets: [read_concurrency: true]],
      ram_copies: [node()]
    ]
  end

  def resolve_conflict(node) do
    copy_store()
  end
end

`

Local cookies
`
%{sessions: {{1559304913698506422, -576460752303422238, 1}, :"feed@127.0.0.1"}}
`

Remote cookies
`
%{sessions:  {{1559304913690428389, -576460752303422718, 1},, :"web@127.0.0.1"}}
`

Stores
`
Stores: [MnesiaNode.Store.Sessions]
`

In this case 
`{local_cookies[data_mapper], remote_cookies[data_mapper]}`

always returns 
`{nil, nil}`

**Comment by beardedeagle** [comment]
closed in #21
