### ISSUE TITLE
How to use with libcluster Kubernetes DNS clustering strategy

### ISSUE THREAD

**Issue by athal7** [beardedeagle/mnesiac#7]
## Question

I'm curious what the best way is to use this with the [libcluster Kubernetes DNS clustering strategy]( https://hexdocs.pm/libcluster/Cluster.Strategy.Kubernetes.DNS.html#content). I see that the hosts are used in the examples, but I won't have the hosts on hand with that clustering strategy. 

Thanks!

**Comment by athal7** [comment]
I have this working with a separate call to `Supervisor.start_link()` for `libcluster`, and then passing in `Node.list()` to the supervisor process for `mnesiac`.

**Comment by erikmocny** [comment]
@athal7 Would you be so kind and provide me some snippet of this configuration? I'm working on same thing. Thanks

**Comment by athal7** [comment]
@erikmocny https://gist.github.com/athal7/3cafa2fa56eeb32fd3282dcfcdae93d9

**Comment by erikmocny** [comment]
@athal7 Thank you, appreciate it.
