### ISSUE TITLE
Remote tables detection not working properly

### ISSUE THREAD

**Issue by fabiosuarez-sumup** [beardedeagle/mnesiac#84]
## Version and Environment

Mnesiac: latest
OS: Alpine Linux v3.16
Elixir: 1.12 OTP 23

## Expected behavior

When initiating new nodes we are expecting mnesia to add copies to the previously existing tables at remote nodes, using:
`:mnesia.add_table_copy/3`

## Actual behavior

The copies are never made, because the rpc call to find remote and local tables is using [`:mnesia.system_info(:tables)`](https://github.com/beardedeagle/mnesiac/blob/381c8e38ab58a30c71ee6c9624bbfdcb7e8a63c0/lib/mnesiac/store_manager.ex#L127-L133) which includes all existent tables (locally and remotely), so the [discovery function](https://github.com/beardedeagle/mnesiac/blob/381c8e38ab58a30c71ee6c9624bbfdcb7e8a63c0/lib/mnesiac/store_manager.ex#L59-L72) which matches against existing tables alway result at a conflicting response, and never copies existing tables to local node. 

## Impact

Once the first node (which created the table in the first place) dies , the table is no longer available, resulting in multiple errors reported as: `{:aborted, {:no_exists, [...]}}`, at every request performed in the remaining living nodes.

## Suggestion

We should use `:mnesia.system_info(:local_tables)` instead, that will allow the matching function to identify that the copy don't exist locally, and properly apply `Store.copy_store/0` properly.

**Comment by rlthompson-godaddy** [comment]
Thanks for filing the issue, getting to this

**Comment by beardedeagle** [comment]
Thanks for filing this, getting to it asap

**Comment by beardedeagle** [comment]
holidays, so getting to pulling in select improvements made in forks. should have something out by end of week.

**Comment by aram0112** [comment]
Hi, I am experiencing this error consistently as well, did a fix for this ever get released?

**Comment by rlthompson-godaddy** [comment]
I'm working on it again now @aram0112

**Comment by beardedeagle** [comment]
This should be addressed now. Sorry for the delay.

**Comment by beardedeagle** [comment]
Closing as this should have been solved in #87. Please open a new issue if you experience any issues with the fix.
